---
#set this to true if you want players to get there old inventory back in a limited ammount of time
get-oldinv-back: true

#within this ammount of time a player can use the command /getoldinventory (if they have one) to get there old inventory back
#time is in seconds
#NOTE: DO NOT ADD ANY LETTERS OR SYMBOLS HERE OR IT WILL MOST DEFINETLY CAUSE PROBLEMS.
oldinv-timer: 60

#only players with this permission can use the commands in this plugin
#OPPED players automatically get this permission
permission: ourinventory.commands.use
...
